title: Guillaume Carraux
description: I  have a website I guess
theme: just-the-docs

url: https://guillaumecarraux.github.io/website

aux_links:
  My Github: https://github.com/guillaumecarraux/website

defaults:
  - scope:
      path: "docs" # empty string means all files in the project
      type: "pages"